### ISSUE TITLE
Script giving "Runtime error"

### ISSUE THREAD

**Issue by theNitchi-zz** [LeobardoArguelles/cbz-merger#1]
I have successfully installed the script and followed the command to merge all cbz into one but it gave this error
![Screenshot 2022-01-15 at 7 49 57 PM](https://user-images.githubusercontent.com/86887160/149625045-3ec2dfa9-05f4-4eb3-ba35-b38225d1d494.png)
I have tried both in virtual and normal environment

PS- I have a alias "py" as python3

**Comment by LeobardoArguelles** [comment]
Hi! Thanks for bringing this to my attention. I managed to replicate that error by having a smaller number of files to merge than the number of cpu's detected by the program. I just uploaded a fix for this bug.

I also noticed that you are using a Mac, which I haven't been able to test the script on, so let me know if you run into any other problems. I would be happy to work them out with you.

**Comment by theNitchi-zz** [comment]
> Hi! Thanks for bringing this to my attention. I managed to replicate that error by having a smaller number of files to merge than the number of cpu's detected by the program. I just uploaded a fix for this bug.
> 
> I also noticed that you are using a Mac, which I haven't been able to test the script on, so let me know if you run into any other problems. I would be happy to work them out with you.

Hello, I tried this again, this is running but giving another error
![Screenshot 2022-01-22 at 2 45 51 PM](https://user-images.githubusercontent.com/86887160/150632518-78198363-bd17-4c5f-a342-f10a45b85ae9.png)

**Comment by LeobardoArguelles** [comment]
Hi! Could you please share with me the full contents of your /User/nitchi/Desktop/manga directory? Some file in there must be causing the error, but I'm not sure how to go around it. Seeing what files are there would help me a great deal to troubleshoot the problem.

**Comment by theNitchi-zz** [comment]
Hello, you were right, the problem was some content in the manga directory because when I tried this on different one, it merged it successfully. But I want to know what is this `zipper` folder mean. because it has the same content as the extracted `manga` folder
![Screenshot 2022-02-17 at 12 10 09](https://user-images.githubusercontent.com/86887160/154419790-e009e91f-446c-497b-a85d-cd21a901ac84.png)

PS- Thank you for making this script :)

**Comment by LeobardoArguelles** [comment]
I am so glad that you got it working! The `zipper` folder is meant to hold all the files in a single folder, without sub-directories, so that the script can merge them in the correct order. It is an intermediate step, so if you don't need it, feel free to delete it.

I'm really happy that you found my script useful!

I'll mark this as closed. If you encounter any further problems, please open a new issue to let me know.
